/** 应用相关sql **/
CHANGE COLUMN `CLASS_ID` `STUDENT_SEQNO` VARCHAR(30) NOT NULL AFTER `STUDENT_NAME`,
CHANGE COLUMN `STUDENT_SEX` `STUDENT_SEX` INT NULL DEFAULT NULL ,
ADD COLUMN `timeOfEnrollment` DATE NULL AFTER `STUDENT_BIRTHDAY`,
ADD COLUMN `dateOFGraduation` DATE NULL AFTER `timeOfEnrollment`;

INSERT INTO `student_manager`.`student_tbl` (`STUDENT_ID`, `STUDENT_NAME`, `STUDENT_SEQNO`, `STUDENT_SEX`, `STUDENT_BIRTHDAY`) VALUES ('1', '张刚', '123', '1', '2015-09-01');
INSERT INTO `student_manager`.`student_tbl` (`STUDENT_ID`, `STUDENT_NAME`, `STUDENT_SEQNO`, `STUDENT_SEX`, `STUDENT_BIRTHDAY`) VALUES ('2', '李四', '124', '1', '2015-09-01');
INSERT INTO `student_manager`.`student_tbl` (`STUDENT_ID`, `STUDENT_NAME`, `STUDENT_SEQNO`, `STUDENT_SEX`, `STUDENT_BIRTHDAY`) VALUES ('3', '王五', '125', '1', '2015-09-01');


ALTER TABLE `student_manager`.`student_tbl`
  CHANGE COLUMN `STUDENT_ID` `STUDENT_ID` BIGINT(10) NOT NULL ,
  CHANGE COLUMN `STUDENT_SEX` `STUDENT_SEX` INT(1) NULL DEFAULT NULL ;

ALTER TABLE `student_manager`.`student_tbl`
  CHANGE COLUMN `STUDENT_ID` `STUDENT_ID` BIGINT(10) NOT NULL AUTO_INCREMENT ;




/** db系统查看sql **/
/** 查看db数据库隔离级别 **/
select @@global.tx_isolation; -- REPEATABLE-READ